# .github/workflows/test.yml
name: Test Only

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  just-test:
    runs-on: ubuntu-latest

    steps:
      - name: befor
        uses: ls
        
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run simple test
        run: echo "✅ Running tests..." && echo "✅ All tests passed!"

      - name: after
        uses: ls
