name: Build and Deploy to Kubernetes

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

        
      # 1️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/test-only:latest .

      # 2️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3️⃣ Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/test-only:latest

      # 4️⃣ Configure kubeconfig
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      # 5️⃣ Update Kubernetes deployment
      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/frontend-deployment frontend=${{ secrets.DOCKER_USERNAME }}/test-only:latest --record
          kubectl rollout status deployment/frontend-deployment
